# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_modular_headers!

  # 穿山甲 SDK 及 Adapter
  pod 'MediatomiOS/SFAdCsjAdapter'
  pod 'Ads-CN-Beta', '6.2.0.0'
  # 百度 SDK 及 Adapter
  pod 'MediatomiOS/SFAdBaiduAdapter'
  pod 'GMBaiduAdapter-Beta', '5.35.1'
  pod 'BaiduMobAdSDK', '5.351'
  # 优量汇 SDK 及 Adapter
  pod 'MediatomiOS/SFAdGdtAdapter'
  pod 'GMGdtAdapter-Beta', '4.14.71.0'
  pod 'GDTMobSDK', '4.14.76'
  # 快手 SDK 及 Adapter
  pod 'MediatomiOS/SFAdKsAdapter'
  pod 'GMKsAdapter-Beta', '3.3.64.0.0'
  pod 'KSAdSDK', '3.3.65'
  # JAD
  pod 'MediatomiOS/SFAdJztAdapter'
  pod 'JADYun', '2.5.12'
  
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
